# This service is built from the Dockerfile in the current directory.
version: '3'
services:
  app_a:
    image: gs://trip-duration-dvc-storages/models/model.joblib
    restart: always
    ports:
      - 8080:8080
  app_b:
    image: gs://trip-duration-dvc-storages/models/model.joblib
    restart: always
    ports:
      - 8080:8080
  app_c:
    image: gs://trip-duration-dvc-storages/models/model.joblib
    restart: always
    ports:
      - 8080:8080