name: CD Pipeline

# If CI and CT's results are sucessful and satisfactory, we deploy the model with CD workflow by pushing a new tag to GitHub.
# perform the below CD jobs automatically whenever a tag is pushed to the repository on last Git commit on master branch.
on:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  Build-and-Push-Docker-Image:
    name: Build and Push Docker Image # to Artifact Registry (GCP)
    # needs: Continuous-Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code from Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # fetch all history. The default is 1, which means Git won't know about the master branch to compare it.

      # Check if the current tagged commit is part of the master branch history, else halts the workflow and marks it as failed.
      - name: Verify Tag is on Master Branch
        run: |
          if git merge-base --is-ancestor HEAD origin/master; then
            echo "Success: Tag is on the master branch. Proceeding with CI/CD..."
          else
            echo "Error: Tag was pushed, but it is NOT on the master branch. Stopping."
            exit 1
          fi

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        id: login-ecr
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker --quiet ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Download model from GCS
        run: |
          gcloud storage cp gs://trip-duration-dvc-storages/models/model.joblib ./models/model.joblib

      - name: Build, tag, and push a Docker image to Artifact Registry
        id: build-image
        env:
          IMAGE_NAME: trip-duration
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GCP_REGION }}
          REPO_NAME: ${{ secrets.GCP_AR_REPO_NAME }}
        run: |
          IMAGE_URI=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
          
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "image=$IMAGE_URI" >> $GITHUB_OUTPUT

  Continuous-Deployment:
    # use self-hosted runner for CD to gain environment control, access internal resources, and manage infrastructure costs.
    name: Continuous Deployment
    runs-on: self-hosted
    needs: Build-and-Push-Docker-Image
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
      
      - name: Pull latest image
        env:
          IMAGE_NAME: trip-duration
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GCP_REGION }}
          REPO_NAME: ${{ secrets.GCP_AR_REPO_NAME }}
        run: |
          IMAGE_URI=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
          docker pull $IMAGE_URI
      
      - name: Delete Previous Container
        run: |
          docker rm -f trip-duration || true

      - name: Run Docker Image to serve users
        env:
            IMAGE_NAME: trip-duration
            PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
            REGION: ${{ secrets.GCP_REGION }}
            REPO_NAME: ${{ secrets.GCP_AR_REPO_NAME }}
        run: |
            IMAGE_URI=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
            docker run -d -p 8080:8080 --ipc="host" --name=$IMAGE_NAME $IMAGE_URI

      # - name: Deploy to Kubernetes
      #   run: kubectl apply -f kubernetes-deployment.yaml

      - name: Cleanup Workspace and Docker
        if: always() # This ensures the cleanup runs even if previous steps fail
        run: |
          echo "Cleaning up untagged/dangling docker images left behind after pulling the new one"
          docker image prune -f
          
          echo "Cleaning up unused docker resources (containers, networks, images) that have been dangling for more than 24 hours"
          docker system prune -af --volumes --filter "until=24h" && find /home/mrvivekkumar7171/actions-runner/_diag/ -name "*.log" -type f -mtime +3 -delete
          
          echo "Cleaning up runner workspace (_work directory) to save disk space"
          rm -rf ${{ github.workspace }}/*