name: CI/CT Pipeline

# perform the below CI/CT jobs automatically whenever a new Git commit is pushed on master branch of the repository.
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  Continuous-Integration:
    # OS to run the pipeline like MacOS, Linux or Windows
    name: Continuous Integration
    runs-on: ubuntu-latest
    # checkout latest commit in the repository, set up python with version and set up cml
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13.5

      - name: CML Setup
        uses: iterative/setup-cml@v3

      # run the below commands for upgrading pip and installing dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      # # run a file
      # - name: Run main file
      #   run: |
      #     python main.py

      - name: Lint code
        run: echo "Linting repository"

      # - name: Run unit tests
      #   run: |
      #     echo "Running unit tests"
      #     python -m unittest discover

      - name: Creating CML Report for unit tests
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          echo "# Report on Scoring metrics of the model" >> report.md
          echo "## Bar Plots" >> report.md
          echo '![](./metrices_bars.png "Bar plot")' >> report.md
          cml comment create report.md